# -*- coding utf-8 -*-
"""

Created by gsiadak @ 12:09 PM 3/2/16

"""

def main():
    str ="CATGCCCTTCTTGCCCTTCGGGGGCCCTTCGCCCTTCCAGCCCTTCACTAGCCCTTCCGGTGCCCTTCACCAGCCCTTCGCCCTTCTGCCCTTCTGAACGCCCTTCGCCCTTCATTGCCCTTCGCCCTTCGCCCTTCAGGCCCTTCGCCCTTCGCCCTTCGGGCCCTTCGCCCTTCGCCCTTCGTTGGGCCCTTCAGCGGCCCTTCTCCTTCGCCCTTCGAGGCCCTTCGTCGCCCTTCGGCCCTTCTGCCCTTCGCCCTTCCTGCCCTTCTGAGGCCCTTCACCTGCCCTTCTCGGCCCTTCGCCCTTCGCCCTTCGCCCTTCTCAGCCCTTCGGGCCCTTCACTGCCCTTCGAAAAGCCGCCCTTCATGCCCTTCGCCCTTCGCCCTTCTAGGCAGCGCCCTTCATGACCCCAGCCCTTCGGGCCCTTCTGCCCTTCGCGCCCTTCACCCGATAAGCCCTTCGGCCCTTCGCCCTTCCGCCCTTCCAAGCCCTTCAAATGCCCTTCGCCCTTCAAATATTATGCCCTTCGCCCTTCTGTCGGAGCCCTTCGCCCTTCTGCCCTTCTGCCCTTCTGCCCTTCGCCCTTCCATAGCCCTTCCTGCCCTTCGGCCCTTCAGGCCCTTCGCCCTTCTGCCACACGCCCTTCGCCCTTCGCCCTTCGGCCCTTCCAGCGCCCTTCGCCCTTCGGGCCCTTCGCCCTTCAGCCCTTCGCCCTTCTGCCCTTCGAACAGCCCTTCACGCGCCCTTCGCCCTTCTTCGCCGCGCCCTTCGGCCCTTCCGCCCTTCGCCCTTCA"
    test = "GCCCTTCGC"

    flag = 0
    locations = []
    for i in range(len(str)):
        if len(str)-i-len(test) < 0:
            break
        else:
            if str[i] == test[0]:
                flag = 0
                for j in range(1, len(test)):
                    if str[i+j] != test[j]:
                        flag = 1
                        break
                if flag == 0:
                    locations.append(i+1)

    print(*locations, " ")





main()